image: ghcr.io/olix0r/ortiofay:v5

load:
  protocols:
    grpc: true
    http: true
  replicas: 1
  linkerdInject: true
  clients: 1
  concurrency: 1
  #requestLimit: 0
  #requestLimitWindow: 1s
  #responseSizes: 0=1024,100=1048576

server:
  services: 1
  replicas: 1
  linkerdInject: true

linkerd: {}
  #proxyImage: ...
  #proxyVersion: ...
